---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br-51
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "br-51",
      "promiscMode": true,
      "ipam": {
          "type": "host-local",
          "ranges": [
              [
                 {
                     "subnet": "51.0.0.0/24",
                     "rangeStart": "51.0.0.5",
                     "rangeEnd": "51.0.0.15"
                 }
              ]
         ],
        "routes": [
                        { "dst": "0.0.0.0/0" }
                ]
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br-52
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "br-52",
      "promiscMode": true,
      "ipam": {
          "type": "host-local",
          "ranges": [
              [
                 {
                     "subnet": "52.0.0.0/24",
                     "rangeStart": "52.0.0.5",
                     "rangeEnd": "52.0.0.15"
                 }
              ]
         ],
                "routes": [
                        { "dst": "0.0.0.0/0" }
                ]
      }
    }'
---
