apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend8
  name: frontend8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend8
  template:
    metadata:
      labels:
        app: frontend8
    spec:
      containers:
      - image: nginx
        name: frontend8
---
